version: '1.5'

services:
    esg-stocks-app:
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard  # Specify the unique Dockerfile name
        ports:
            - 8080:5000
        volumes:
            - ./dashboard:/app
            - ./data:/data
        environment:
          FLASK_APP: app.py
          FLASK_ENV: development  # This enables debug mode 
            # - PYTHONPATH=/app
        working_dir: /app
        depends_on:
            esg-stocks-db:
                condition: service_healthy
    
    jupyter:
        build:
            context: .
            dockerfile: notebook/Dockerfile_notebook
        ports:
            - 8888:8888
        volumes:
            - ./notebook:/notebook
            - ./data:/data
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - NB_USER=team13
            - CHOWN_HOME=yes
        working_dir: /notebook
    
    esg-stocks-db:
        image: postgres:16
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=team13
            - POSTGRES_PASSWORD=team13
            - POSTGRES_DB=esg-stocks-database
        volumes:
            - esg-stocks-db-data:/var/lib/postgresql/data/
        container_name: esg-stocks-db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 3s
            timeout: 60s
            retries: 10
            start_period: 80s

volumes:
    esg-stocks-db-data:
