# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents to /app
COPY ./dashboard /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py
# Automatically enables debug mode
ENV FLASK_ENV=development  

# Run the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
